name: Docker-Compose Remote Deployment
author: Wernich Bekker<wernich.bekker+dev@gmail.com>
description: A GitHub Action that supports docker-compose on remote hosts
inputs:
  remote_docker_host:
    description: Remote Docker host ie (user@host)
    required: true
  ssh_public_key:
    description: Remote Docker SSH public key
  ssh_private_key:
    description: SSH private key used to connect to the docker host
  tailscale_ssh:
    description: Use Tailscale SSH to conncet to the server with managed SSH keys
    default: 'false'
  args:
    description: Deployment command args.
    required: true
  compose_file_path:
    description: path for Docker compose file used. Default is is repo root(docker-compose.yml)
    required: false
  ssh_port:
    description: The ssh port of the server. Default is 22
    required: false
  upload_directory:
    description: when enabled, uploads entire docker directory, useful for configuration files needed along the container
    default: 'false'
  docker_compose_directory:
    description: specifies which directory to upload, needed for upload_directory
    required: false
  docker_login_password:
    description: The docker login password
    required: false
  docker_swarm:
    description: enables docker swarm mode (docker stack deploy), defaults to false
    default: 'false'
  docker_login_user:
    description: The docker login user
    required: false
  docker_login_registry:
    description: The docker login registry
    required: false

runs:
  using: docker
  image: 'Dockerfile'


branding:
  icon: send
  color: green

